# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
#branches:
  # whitelist
  # only:
    # - temp

  # blacklist
  #except:
    #- gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
- git config --global core.autocrlf input
# clone directory
clone_folder: c:\projects\Json

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 30                      # clone entire repository history if not defined

# environment variables
environment:
  VisualStudioVersion: 14


# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config

# scripts that run after cloning repository
install:
  - cmd: nuget sources add -Name NuGetV3 -Source  https://api.nuget.org/v3/index.json

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  # parallel: true                  # enable MSBuild parallel builds
  project: c:\projects\Json\Newtonsoft.Json.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal


# scripts to run before build
before_build:
- appveyor-retry nuget restore "c:\projects\Json\.nuget\packages.config" -PackagesDirectory "c:\projects\Json\packages" -DisableParallelProcessing

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

# to disable automatic builds
#build: off

# scripts to run before tests
before_test:
  # - echo script1
- ps: >-
    $env:CLIENT_TESTS_EXIT_CODE = 0
 
# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:


# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off


#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  # - do something

# on build failure
on_failure:
  # - do something

# after build failure or success
on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  - provider: Slack
    auth_token:
      secure: zSdvelf8KpJg8tlCgYGPNygKefpXDGYETPAy5LX/xNTKcvcyt0V0hU4ISNUIEEKE
    channel: 'bridge-github'
    on_build_status_changed: true
    on_build_success: true
    on_build_failure: true

